version: '3'

services:

  app:
    image: 'tmvdl/android:app'
    build: './src/app'

  api29:
    image: 'tmvdl/android:api29'
    build: './src/api29'

  # sdk30:
  #   image: 'tmvdl/android:sdk30'
  #   build: './src/sdk30'

  flutter:
    image: 'tmvdl/android:flutter'
    build: './src/flutter'

  ionic:
    image: 'tmvdl/android:ionic'
    build: './src/ionic'

  react-native:
    image: 'tmvdl/android:react-native'
    build: './src/react-native'
