name: Pushing

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}
      -
        name: Build and Tag
        run: sh build.sh 30 angular cordova ionic react-native
      -
        name: Push
        run: docker push tmvdl/android -a
