name: Docker Push

on:
  schedule:
    - cron: '10 10 * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Build and Tag
        run: sh env/build.sh

      - name: Docker Push
        run: docker push tmvdl/android -a
