name: Docker Push

on:
  schedule:
    - cron: '10 10 * * *'
  workflow_dispatch:
  push:
    branches: 
      - 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Build Docker images
        run: sh env/build.sh

      - name: Push images to Docker Hub
        run: sh env/docker-push.sh
